USE PROJECT;
CREATE TABLE BOOKING(
	BOOKING_ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	FULL_NAME NVARCHAR(100) NOT NULL,
	EMAIL NVARCHAR(100) NOT NULL,
	DESTINATION VARCHAR(11) NOT NULL,
	TRAVEL_DATE DATE NOT NULL,
	NUMBER_OF_TRAVELERS INT NOT NULL,
	CREATED_AT DATETIME DEFAULT GETDATE()
);

USE PROJECT;
SELECT*
FROM BOOKING;